# Generated by Django 5.0.6 on 2024-05-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmashData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fighterNumber', models.CharField(max_length=255)),
                ('fighterName', models.CharField(max_length=255)),
            ],
        ),
    ]
