# Generated by Django 5.0.6 on 2024-06-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskeywheel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ww_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=255)),
            ],
        ),
    ]
