# Generated by Django 5.0.6 on 2024-06-19 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskeywheel', '0002_ww_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='ww_member',
            name='date_created',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='ww_member',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
